language: java
jdk:
  - oraclejdk8

install: true

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    - PATH=/usr/lib/jvm/java-8-openjdk-amd64/bin:$PATH
    
script: mvn -DskipTests=true clean verify
